### ISSUE TITLE
The frame the point cloud lies in

### ISSUE THREAD

**Issue by ptrnn** [val-iisc/3d-lmnet#10]
Hello, thank you for your excellent work. I have a question about the dataset preparation. Say if we have access to the depth image and camera parameters (intrinsic and extrinsic), we backproject depth image to 3d space using intrinsic matrix and transform it from camera frame to world frame using extrinsic matrix. Do sampled ground truth point cloud and point cloud recovered from depth lie in the same frame? Or the ground truth pc lies in their own body frame?

**Comment by priyankamandikal** [comment]
Hi, it shouldn't be a problem if you use depth maps to obtain the point cloud in the world frame. Note that, we use the point cloud in a canonical frame without rotation, so you would have to factor out the camera rotation if you want to use canonical orientations like we do.

**Comment by ptrnn** [comment]
Hi Priyanka, thank you for your reply. Just to clarify, your work use the same ground truth for one object captured from different viewpoints while PSGN used different ground truths for that, right?

**Comment by mayankgrwl97** [comment]
That's correct.
