### ISSUE TITLE
Request for point clouds generation method from meshes

### ISSUE THREAD

**Issue by xiaomingjie** [val-iisc/3d-lmnet#2]
Sorry to bother you again. You said that you will provide the ground truth point clouds before but now due to memory restrains you give ShapeNet meshes instead. I totally understand that but could you release your point clouds generation method from meshes and how to package your rendered images, point clouds together to get training started? I supposed that here isn't clear enough to use your dataset to start training.

**Comment by priyankamandikal** [comment]
Hi, to enable easy training, we have now provided links to download the entire dataset (training+validation) for input images and ground truth point clouds. Please refer to the instructions for downloading them.
