### ISSUE TITLE
it is very new idea in 3D reconstruction,but would u like to share me with the model apply to the real-world data,like u said in paper,and in my experience it did't work,could u share me with the details?Thanks to your reply.

### ISSUE THREAD

**Issue by AmyWan** [val-iisc/3d-lmnet#4]

**Comment by AmyWan** [comment]
I am sorry for ask again.I want to know how to use the nature images to test the model.but  the demo is for shapnet.

**Comment by priyankamandikal** [comment]
For testing on natural images, be sure to mask out the background, then crop and resize the image to 128 x 128 dimension (keeping the aspect ratio same) before passing it through 3D-LMNet.

**Comment by AmyWan** [comment]
> mask out

ok,I directly resize the nature image(mask out the background) to 128 *128 with function of opencv resize,is it right? I didnt do crop ,dose it have influeuce?

**Comment by priyankamandikal** [comment]
I have now updated the repository with the code for generating results on the real-world Pix3D dataset. Please follow the updated instructions for viewing the results. The specific pre-processing perfomed on these natural images is present here: https://github.com/val-iisc/3d-lmnet/blob/master/metrics.py#L92
