### ISSUE TITLE
could you provide how to visualize the PSGN result like your paper shows 

### ISSUE THREAD

**Issue by ransun1004** [val-iisc/3d-lmnet#5]
Hello! your idea is novel ,  and the result has great improved , but I cant recieve the reconstyructed point clouds of PSGN, could you provide how to visualize the PSGN result like your paper shows ?  Thank you!

**Comment by priyankamandikal** [comment]
Hi, we have already provided code for visualizing point clouds generated by our method. You can view it by running the command:
bash scripts/demo_lm.sh

For visualizing results generated by PSGN, please refer to the instructions provided  in their repository.

**Comment by ransun1004** [comment]
thank you, but I can't achieve the trained model(several .ckpt files), and I can't connect to the PSGN author , could you provide these trained model for me?
by the way, I also want to know how to train the model with PIX3D dataset?
sorry to bother you, wish to receive your reply,thank you!

**Comment by ransun1004** [comment]
thank you, but I can't achieve the trained model(several .ckpt files), and I can't connect to the PSGN author , could you provide these trained model for me?
by the way, I also want to know how to train the model with PIX3D dataset?
sorry to bother you, wish to receive your reply,thank you!

**Comment by ransun1004** [comment]
thank you, but I can't achieve the trained model(several .ckpt files), and I can't connect to the PSGN author , could you provide these trained model for me?
by the way, I also want to know how to train the model with PIX3D dataset?
sorry to bother you, wish to receive your reply,thank you!
My email : 1647748349@qq.com
